# Generated by Django 5.2.8 on 2025-11-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="organizador",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="titulo",
        ),
        migrations.AddField(
            model_name="evento",
            name="nombre",
            field=models.CharField(default="Sin nombre", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evento",
            name="fecha",
            field=models.DateField(),
        ),
    ]
